### ISSUE TITLE
Troubleshoot adding and saving new items

### ISSUE THREAD

**Issue by karenmajewicz** [BTAA-Geospatial-Data-Project/geomg#91] opened 2020-12-17 20:17 UTC
I was not able to create a new item using the form editor.  In my email error, I received this message:

stack level too deep
  app/models/document.rb:186:in `transition_publication_state'

**Comment by karenmajewicz** [comment] 2021-01-08 16:58
Could this have been related to the (now-solved) problem of records being suppressed in GEOMG when the checkboxes were not working? It occurred when I was wrestling with that issue and tried to repeatedly create a new record.

However, just now, I tried to create a new record using a Slug already present in the database. I then got a descriptive error in my email "  PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_kithe_models_on_friendlier_id", so maybe that wasn't it.

**Comment by ewlarson** [comment] 2021-01-08 17:01
I think the original issue _might_ have been all that work to normalize publication state values... but that's just a guess.

**Comment by karenmajewicz** [comment] 2021-01-08 17:13
Hmm, I think it must have been something along those lines because I am able to create new records now without issue. Can I close this issue?

**Comment by ewlarson** [comment] 2021-01-08 17:13
Yeah. Closing as unable to reproduce now.

**Comment by karenmajewicz** [comment] 2021-01-08 22:16
OK, I just reproduced the error. I think what happens is if you try to create a new record and set publication state immediately to "published", this stack level error happens. If I leave the default publication state as "draft," it is fine.

**Comment by karenmajewicz** [comment] 2021-01-08 22:17
Not a huge problem, but maybe something to address later on.

**Comment by ewlarson** [comment] 2021-05-06 13:54
The form has been updated. You cannot set publication state on a new item. Instead you create the object and its default state becomes "draft". You then can update it to "published".

Kinda odd, but the state machine library we're using seems to only allow objects to walk through state (draft => published), instead of being created as published.

**Closed** 2021-07-09 15:11 UTC
Labels: Error reports, priority:medium, type:bug
